spring.application.name=olastore

server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/olastore}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}

logging.level.com.ola.olastore=DEBUG

openapi.version=${API_VERSION:1.0.0}
openapi.name=${API_NAME:olastore}
openapi.description=${API_DESCRIPTION:Backend API for managing Products.}

#===== CLOUDINARY CONFIGURATION =======
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api_key=${CLOUDINARY_API_KEY:}
cloudinary.api_secret=${CLOUDINARY_API_SECRET:}
cloudinary.secure=true
